name: CI

on:
  schedule:
    - cron:  "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    name: File creator job
    steps:
    - uses: actions/checkout@v1
    - shell: bash
      run: |
        echo "Zafer" > test.txt
    - name: Upload file
      uses: actions/upload-artifact@v2
      with:
        name: results.txt
        path: test.txt