name: "Hello"

on:
  schedule:
    - cron:  '*/2 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Get the output time
      run: echo "Patates"
    - shell: bash
      run: |
        echo "Zafer" > main.txt