name: CI

on:
  schedule:
    - cron:  "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v1
    - name: Patates
      run: echo "Patates" > patatesList.txt